server
{
    listen 443 ssl;

    server_name localhost shadria-.42.fr;

    ssl_certificate /etc/nginx/ssl/shadria.crt;
    
    ssl_certificate_key /etc/nginx/ssl/shadria.key;

    ssl_protocols TLSv1.3 TLSv1.2;
    root /var/www/html;
    index index.php;

    access_log /var/log/nginx/nginx-access.log;
    error_log /var/log/nginx/nginx-error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ .php$ {
        fastcgi_pass wordpress:9000;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
